### ISSUE TITLE
Improve login proposal 

### ISSUE THREAD

**Issue by hikarihacks** [akrol98/DCQAE#2]
I'm not quite sure how to implement it, but I have an idea for automatizing the login process

Here is the link where the login form is : https://www.freekigames.com/auth/popup/login.theform

This is the one that gets displayed when the login button on the main page is pressed.
The following are the IDs for the main elements :

Username field : userName
Password field : password
Log in button : bp_login 

In the extension options, we could set a username and a password.
Or maybe even accept a file with usernames and passwords

**Comment by akrol98** [comment]
Unfortunately I'm not going to implement this for a few reasons. Mainly security, I don't want to be in charge of users accounts. There are extensions out there that will autofill login credentials. I personally use LastPass
